source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

#general rails gem
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
#'pg' for postgres
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
#encoding passwords
gem 'bcrypt', '~> 3.1.7'
#to serialize new user data
gem 'active_model_serializers', '0.9.3'
#json web token
gem 'jwt' , '~> 2.1'
gem 'faker', '~>1.9'

gem 'bootsnap', '>= 1.4.2', require: false
#enabling cross origin resource sharing 
gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
